spring:
  application:
    name: mobilePhoneBooking
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
      initialize: true
      schema: data.sql
      data: data.sql
server:
  port: 8080
  host: localhost
app:
  token: token
  phones: Samsung Galaxy S9,Samsung Galaxy S8,Samsung Galaxy S7,Motorola Nexus 6,LG Nexus 5X,Huawei Honor 7X,Apple iPhone X,Apple iPhone 8,Apple iPhone 4s,Nokia 3310
  endpoint:
    phone:
      booking: /api/v1/phone/book/{phoneId}/{person}
      return: /api/v1/phone/return/{phoneId}